const actionTypes = {
  SET_SCREEN: 'SET_SCREEN',
  FETCH_GIST_REQUEST: 'FETCH_GIST_REQUEST',
  FETCH_GIST_SUCCESS: 'FETCH_GIST_SUCCESS',
  FINISH_BOOT: 'FINISH_BOOT',
  UPDATE_GAME: 'UPDATE_GAME',
  TOKEN_REQUEST: 'TOKEN_REQUEST',
  TOKEN_SUCCESS: 'TOKEN_SUCCESS',
  SET_NEXT_ACTION: 'SET_NEXT_ACTION',
  CLEAR_NEXT_ACTION: 'CLEAR_NEXT_ACTION'

  // CREATE_GIST_REQUEST: 'CREATE_GIST_REQUEST',
  // CREATE_GIST_SUCCESS: 'CREATE_GIST_SUCCESS',
}

export default actionTypes
