const actionTypes = {
  SET_SCREEN: 'SET_SCREEN',
  FETCH_GIST_REQUEST: 'FETCH_GIST_REQUEST',
  FETCH_GIST_SUCCESS: 'FETCH_GIST_SUCCESS',
  FINISH_BOOT: 'FINISH_BOOT',
  UPDATE_GAME: 'UPDATE_GAME',
  NEW_GAME: 'NEW_GAME',
  TOKEN_REQUEST: 'TOKEN_REQUEST',
  TOKEN_SUCCESS: 'TOKEN_SUCCESS',
  SET_NEXT_ACTION: 'SET_NEXT_ACTION',
  CLEAR_NEXT_ACTION: 'CLEAR_NEXT_ACTION',
  SAVE_GIST_REQUEST: 'SAVE_GIST_REQUEST',
  SAVE_GIST_SUCCESS: 'SAVE_GIST_SUCCESS',
  UPDATE_SFX: 'UPDATE_SFX'
}

export default actionTypes
