const actionTypes = {
  SET_SCREEN: 'SET_SCREEN',
  FETCH_GIST_REQUEST: 'FETCH_GIST_REQUEST',
  FETCH_GIST_SUCCESS: 'FETCH_GIST_SUCCESS'

  // INPUT_TERMINAL_COMMAND: 'INPUT_TERMINAL_COMMAND',
  // CLEAR_TERMINAL: 'CLEAR_TERMINAL',
  // UPDATE_GAME: 'UPDATE_GAME',
  // TOKEN_REQUEST: 'TOKEN_REQUEST',
  // TOKEN_SUCCESS: 'TOKEN_SUCCESS',
  // CREATE_GIST_REQUEST: 'CREATE_GIST_REQUEST',
  // CREATE_GIST_SUCCESS: 'CREATE_GIST_SUCCESS',
  // SET_NEXT_ACTION: 'SET_NEXT_ACTION',
  // CLEAR_NEXT_ACTION: 'CLEAR_NEXT_ACTION'
}

export default actionTypes
